[package]
name = "encryptr"
version = "0.1.0"
edition = "2024"

[dependencies]
bimap = "0.6.3"
bit_ops = "0.2.3"
itertools = "0.14.0"
miller_rabin = "1.1.1"
num-bigint = { version = "0.4.6", features = ["rand"] }
num-modular = "0.6.1"
rand = "0.8.5"
sealed = "0.6.0"
tap = "1.0.1"
thiserror = "2.0.18"
der = { version = "0.7", features = ["std", "derive", "pem"] }
pem-rfc7468 = { version = "0.7.0", features = ["std"] }
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5"
clap_mangen = "0.2"
anyhow = "1.0"
hex = "0.4"
base64 = "0.22"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.15"
